services:
  app:
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./php/app:/var/www/html
    networks:
      - app-nw
    depends_on:
      - db
  web:
    image: nginx:1.26.2
    ports: 
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./php/app:/var/www/html
    networks:
      - app-nw
    depends_on:
      - app
  db:
    image: mysql:8.4
    env_file:
      - db.env
    networks:
      - app-nw
  
networks:
  app-nw:
    driver: bridge